# Generated by Django 5.1.5 on 2025-03-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tool'),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='value',
            field=models.TextField(),
        ),
    ]
