apiVersion: v1
kind: Secret
metadata:
  name: {{ include "serverlesstool.fullname" . }}
  labels:
    {{- include "serverlesstool.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.env }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }} 